package ntut.csie.TestAspectPackage;

import org.junit.Test;
import ntut.csie.RobustaUtils.AspectJSwitch;
import org.junit.Assert;
import ntut.csie.failFastUT.UnprotectedMain.CreateUTOutsideTryExample;

public class testCreateUTOutsideTryExampleMethodUseAspetctJ {

	private AspectJSwitch aspectJSwitch = AspectJSwitch.getInstance();

	@Test
	public void testDueToThrowIO3MainShouldNotThrowAnyException() {
		aspectJSwitch.initResponse();
		aspectJSwitch.addResponse("throwIO3/f(RuntimeException)");
		aspectJSwitch.toFirstResponse();
		try{
			String[] args={};
			CreateUTOutsideTryExample.main(args);
		}catch (Throwable e) {
			Assert.fail(e.getMessage());
		}
	}
	@Test
	public void testDueToPrint1MainShouldNotThrowAnyException() {
		aspectJSwitch.initResponse();
		aspectJSwitch.addResponse("print1/f(RuntimeException)");
		aspectJSwitch.toFirstResponse();
		try{
			String[] args={};
			CreateUTOutsideTryExample.main(args);
		}catch (Throwable e) {
			Assert.fail(e.getMessage());
		}
	}
	
}